server:
  port: 8080
spring:
  main:
    banner-mode: off
  application:
    name: producer
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

logging:
  level:
    root: warn
    org:
      apache:
        kafka: off
    com:
      mak:
        producer: info
